name: coins_env
channels:
  - pytorch
  - pytorch3d
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.7
  - mkl=2021.4.0
  - gxx_linux-64=9.5.0
  - gcc_linux-64=9.5.0
  - cudatoolkit-dev=11.3
  - cudatoolkit=11.3
  - pytorch::pytorch=1.11.0
  - pytorch3d::pytorch3d
  - pytorch-lightning
  - torchvision
  - trimesh
  - tqdm
  - opencv
  - scikit-learn
  - matplotlib
  - Pillow
  - PyYAML
  - numpy
  - scipy
  - pandas
  - tensorboardX
  - libxcrypt
  - boost
  - pip